// Centralized Dummy Data for SISI Learning Management System
// This file contains all mock data required for the application

// ==================== MODULES DATA ====================
// Minimal 10 modules required
export const modules = [
  {
    id: 1,
    code: "WEB101",
    title: "Introduction to Web Development",
    description: "Learn the fundamentals of web development including HTML, CSS, and JavaScript basics",
    instructor: "Dr. Ahmad Rahman",
    duration: "8 weeks",
    level: "Beginner",
    topics: ["HTML5", "CSS3", "JavaScript Basics", "Responsive Design"],
    enrolledStudents: 125,
    rating: 4.8,
    status: "active",
    startDate: "2026-01-15",
    endDate: "2026-03-10",
  },
  {
    id: 2,
    code: "WEB201",
    title: "Advanced JavaScript & ES6+",
    description: "Master modern JavaScript features, async programming, and advanced concepts",
    instructor: "Sarah Johnson",
    duration: "6 weeks",
    level: "Intermediate",
    topics: ["ES6+ Features", "Async/Await", "Promises", "Modules", "OOP in JS"],
    enrolledStudents: 98,
    rating: 4.9,
    status: "active",
    startDate: "2026-01-20",
    endDate: "2026-03-05",
  },
  {
    id: 3,
    code: "REACT101",
    title: "React Fundamentals",
    description: "Build modern web applications with React.js, hooks, and component-based architecture",
    instructor: "Michael Chen",
    duration: "10 weeks",
    level: "Intermediate",
    topics: ["Components", "Hooks", "State Management", "React Router", "Context API"],
    enrolledStudents: 156,
    rating: 4.7,
    status: "active",
    startDate: "2026-02-01",
    endDate: "2026-04-15",
  },
  {
    id: 4,
    code: "NODE101",
    title: "Node.js & Express Backend Development",
    description: "Learn server-side JavaScript with Node.js and build RESTful APIs with Express",
    instructor: "Dr. Ahmad Rahman",
    duration: "8 weeks",
    level: "Intermediate",
    topics: ["Node.js Core", "Express.js", "REST APIs", "Authentication", "MongoDB"],
    enrolledStudents: 87,
    rating: 4.6,
    status: "active",
    startDate: "2026-02-10",
    endDate: "2026-04-05",
  },
  {
    id: 5,
    code: "DB101",
    title: "Database Design & SQL",
    description: "Master relational database design, SQL queries, and database optimization",
    instructor: "Prof. David Lee",
    duration: "7 weeks",
    level: "Beginner",
    topics: ["Database Design", "SQL Queries", "Normalization", "Indexing", "Transactions"],
    enrolledStudents: 142,
    rating: 4.5,
    status: "active",
    startDate: "2026-01-25",
    endDate: "2026-03-15",
  },
  {
    id: 6,
    code: "MOB101",
    title: "Mobile App Development with React Native",
    description: "Create cross-platform mobile applications using React Native",
    instructor: "Lisa Wang",
    duration: "12 weeks",
    level: "Advanced",
    topics: ["React Native", "Navigation", "Native Modules", "State Management", "Deployment"],
    enrolledStudents: 76,
    rating: 4.8,
    status: "active",
    startDate: "2026-02-15",
    endDate: "2026-05-10",
  },
  {
    id: 7,
    code: "DEVOPS101",
    title: "DevOps & CI/CD Fundamentals",
    description: "Learn modern DevOps practices, containerization, and continuous deployment",
    instructor: "Robert Smith",
    duration: "6 weeks",
    level: "Intermediate",
    topics: ["Docker", "Kubernetes", "CI/CD", "Git", "Cloud Deployment"],
    enrolledStudents: 64,
    rating: 4.7,
    status: "active",
    startDate: "2026-03-01",
    endDate: "2026-04-12",
  },
  {
    id: 8,
    code: "UIUX101",
    title: "UI/UX Design Principles",
    description: "Design beautiful and user-friendly interfaces with modern design principles",
    instructor: "Emma Martinez",
    duration: "8 weeks",
    level: "Beginner",
    topics: ["Design Thinking", "Wireframing", "Prototyping", "User Research", "Figma"],
    enrolledStudents: 112,
    rating: 4.9,
    status: "active",
    startDate: "2026-01-18",
    endDate: "2026-03-12",
  },
  {
    id: 9,
    code: "SEC101",
    title: "Web Security & Best Practices",
    description: "Protect your applications from common security vulnerabilities",
    instructor: "Dr. Ahmad Rahman",
    duration: "5 weeks",
    level: "Advanced",
    topics: ["OWASP Top 10", "Authentication", "Encryption", "XSS", "CSRF", "SQL Injection"],
    enrolledStudents: 53,
    rating: 4.6,
    status: "active",
    startDate: "2026-03-05",
    endDate: "2026-04-10",
  },
  {
    id: 10,
    code: "TEST101",
    title: "Software Testing & Quality Assurance",
    description: "Master unit testing, integration testing, and test-driven development",
    instructor: "Jennifer Brown",
    duration: "6 weeks",
    level: "Intermediate",
    topics: ["Unit Testing", "Jest", "React Testing Library", "E2E Testing", "TDD"],
    enrolledStudents: 89,
    rating: 4.7,
    status: "active",
    startDate: "2026-02-20",
    endDate: "2026-04-02",
  },
  {
    id: 11,
    code: "ALGO101",
    title: "Data Structures & Algorithms",
    description: "Essential computer science concepts for efficient problem solving",
    instructor: "Prof. David Lee",
    duration: "10 weeks",
    level: "Intermediate",
    topics: ["Arrays", "Trees", "Graphs", "Sorting", "Big O Notation"],
    enrolledStudents: 134,
    rating: 4.8,
    status: "active",
    startDate: "2026-01-22",
    endDate: "2026-04-05",
  },
  {
    id: 12,
    code: "PYTHON101",
    title: "Python Programming for Beginners",
    description: "Learn Python from scratch with hands-on projects",
    instructor: "Sarah Johnson",
    duration: "8 weeks",
    level: "Beginner",
    topics: ["Python Basics", "Functions", "OOP", "Libraries", "File I/O"],
    enrolledStudents: 167,
    rating: 4.9,
    status: "active",
    startDate: "2026-01-10",
    endDate: "2026-03-05",
  },
];

// ==================== QUIZZES DATA ====================
// Minimal 30 quizzes required
export const quizzes = [
  {
    id: 1,
    moduleId: 1,
    title: "HTML Basics Quiz",
    description: "Test your understanding of HTML fundamentals",
    difficulty: "Easy",
    duration: 20,
    passingScore: 70,
    totalQuestions: 10,
    totalPoints: 100,
    attempts: 245,
    averageScore: 82,
    status: "published",
  },
  {
    id: 2,
    moduleId: 1,
    title: "CSS Fundamentals",
    description: "Assess your CSS knowledge",
    difficulty: "Easy",
    duration: 25,
    passingScore: 70,
    totalQuestions: 12,
    totalPoints: 120,
    attempts: 198,
    averageScore: 78,
    status: "published",
  },
  {
    id: 3,
    moduleId: 1,
    title: "JavaScript Introduction",
    description: "Basic JavaScript concepts and syntax",
    difficulty: "Medium",
    duration: 30,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 176,
    averageScore: 74,
    status: "published",
  },
  {
    id: 4,
    moduleId: 2,
    title: "ES6 Features Quiz",
    description: "Modern JavaScript ES6+ features",
    difficulty: "Medium",
    duration: 35,
    passingScore: 75,
    totalQuestions: 18,
    totalPoints: 180,
    attempts: 134,
    averageScore: 79,
    status: "published",
  },
  {
    id: 5,
    moduleId: 2,
    title: "Async JavaScript",
    description: "Promises, async/await, and callbacks",
    difficulty: "Hard",
    duration: 40,
    passingScore: 80,
    totalQuestions: 20,
    totalPoints: 200,
    attempts: 112,
    averageScore: 71,
    status: "published",
  },
  {
    id: 6,
    moduleId: 3,
    title: "React Components",
    description: "Understanding React component architecture",
    difficulty: "Medium",
    duration: 30,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 189,
    averageScore: 81,
    status: "published",
  },
  {
    id: 7,
    moduleId: 3,
    title: "React Hooks Mastery",
    description: "useState, useEffect, and custom hooks",
    difficulty: "Hard",
    duration: 45,
    passingScore: 80,
    totalQuestions: 20,
    totalPoints: 200,
    attempts: 156,
    averageScore: 76,
    status: "published",
  },
  {
    id: 8,
    moduleId: 3,
    title: "React Router Quiz",
    description: "Navigation and routing in React applications",
    difficulty: "Medium",
    duration: 25,
    passingScore: 75,
    totalQuestions: 12,
    totalPoints: 120,
    attempts: 143,
    averageScore: 80,
    status: "published",
  },
  {
    id: 9,
    moduleId: 4,
    title: "Node.js Core Concepts",
    description: "Understanding Node.js fundamentals",
    difficulty: "Medium",
    duration: 30,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 98,
    averageScore: 77,
    status: "published",
  },
  {
    id: 10,
    moduleId: 4,
    title: "Express.js Routing",
    description: "Building APIs with Express",
    difficulty: "Medium",
    duration: 35,
    passingScore: 75,
    totalQuestions: 18,
    totalPoints: 180,
    attempts: 87,
    averageScore: 79,
    status: "published",
  },
  {
    id: 11,
    moduleId: 4,
    title: "REST API Design",
    description: "RESTful API principles and best practices",
    difficulty: "Hard",
    duration: 40,
    passingScore: 80,
    totalQuestions: 20,
    totalPoints: 200,
    attempts: 76,
    averageScore: 73,
    status: "published",
  },
  {
    id: 12,
    moduleId: 5,
    title: "SQL Basics",
    description: "Fundamental SQL queries and operations",
    difficulty: "Easy",
    duration: 25,
    passingScore: 70,
    totalQuestions: 12,
    totalPoints: 120,
    attempts: 178,
    averageScore: 83,
    status: "published",
  },
  {
    id: 13,
    moduleId: 5,
    title: "Database Normalization",
    description: "Understanding normal forms and design",
    difficulty: "Hard",
    duration: 40,
    passingScore: 80,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 124,
    averageScore: 72,
    status: "published",
  },
  {
    id: 14,
    moduleId: 5,
    title: "Advanced SQL Queries",
    description: "Joins, subqueries, and aggregations",
    difficulty: "Hard",
    duration: 45,
    passingScore: 80,
    totalQuestions: 20,
    totalPoints: 200,
    attempts: 103,
    averageScore: 70,
    status: "published",
  },
  {
    id: 15,
    moduleId: 6,
    title: "React Native Basics",
    description: "Introduction to mobile development",
    difficulty: "Medium",
    duration: 30,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 89,
    averageScore: 78,
    status: "published",
  },
  {
    id: 16,
    moduleId: 6,
    title: "React Navigation",
    description: "Navigation patterns in React Native",
    difficulty: "Medium",
    duration: 35,
    passingScore: 75,
    totalQuestions: 18,
    totalPoints: 180,
    attempts: 76,
    averageScore: 76,
    status: "published",
  },
  {
    id: 17,
    moduleId: 7,
    title: "Docker Fundamentals",
    description: "Containerization with Docker",
    difficulty: "Medium",
    duration: 30,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 67,
    averageScore: 79,
    status: "published",
  },
  {
    id: 18,
    moduleId: 7,
    title: "CI/CD Pipeline Setup",
    description: "Continuous integration and deployment",
    difficulty: "Hard",
    duration: 40,
    passingScore: 80,
    totalQuestions: 20,
    totalPoints: 200,
    attempts: 54,
    averageScore: 74,
    status: "published",
  },
  {
    id: 19,
    moduleId: 8,
    title: "Design Thinking Process",
    description: "User-centered design methodology",
    difficulty: "Easy",
    duration: 25,
    passingScore: 70,
    totalQuestions: 12,
    totalPoints: 120,
    attempts: 134,
    averageScore: 85,
    status: "published",
  },
  {
    id: 20,
    moduleId: 8,
    title: "Wireframing & Prototyping",
    description: "Creating effective wireframes",
    difficulty: "Medium",
    duration: 30,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 112,
    averageScore: 82,
    status: "published",
  },
  {
    id: 21,
    moduleId: 9,
    title: "OWASP Top 10",
    description: "Common web security vulnerabilities",
    difficulty: "Hard",
    duration: 45,
    passingScore: 80,
    totalQuestions: 20,
    totalPoints: 200,
    attempts: 67,
    averageScore: 71,
    status: "published",
  },
  {
    id: 22,
    moduleId: 9,
    title: "Authentication & Authorization",
    description: "Secure user authentication methods",
    difficulty: "Hard",
    duration: 40,
    passingScore: 80,
    totalQuestions: 18,
    totalPoints: 180,
    attempts: 58,
    averageScore: 73,
    status: "published",
  },
  {
    id: 23,
    moduleId: 10,
    title: "Unit Testing with Jest",
    description: "Writing effective unit tests",
    difficulty: "Medium",
    duration: 35,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 92,
    averageScore: 80,
    status: "published",
  },
  {
    id: 24,
    moduleId: 10,
    title: "React Testing Library",
    description: "Testing React components",
    difficulty: "Medium",
    duration: 35,
    passingScore: 75,
    totalQuestions: 18,
    totalPoints: 180,
    attempts: 84,
    averageScore: 77,
    status: "published",
  },
  {
    id: 25,
    moduleId: 11,
    title: "Arrays & Strings",
    description: "Common array and string problems",
    difficulty: "Medium",
    duration: 40,
    passingScore: 75,
    totalQuestions: 20,
    totalPoints: 200,
    attempts: 156,
    averageScore: 76,
    status: "published",
  },
  {
    id: 26,
    moduleId: 11,
    title: "Trees & Graphs",
    description: "Tree and graph algorithms",
    difficulty: "Hard",
    duration: 50,
    passingScore: 80,
    totalQuestions: 25,
    totalPoints: 250,
    attempts: 123,
    averageScore: 69,
    status: "published",
  },
  {
    id: 27,
    moduleId: 11,
    title: "Sorting Algorithms",
    description: "Understanding sorting techniques",
    difficulty: "Medium",
    duration: 35,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 145,
    averageScore: 78,
    status: "published",
  },
  {
    id: 28,
    moduleId: 12,
    title: "Python Basics",
    description: "Python syntax and fundamentals",
    difficulty: "Easy",
    duration: 25,
    passingScore: 70,
    totalQuestions: 12,
    totalPoints: 120,
    attempts: 198,
    averageScore: 84,
    status: "published",
  },
  {
    id: 29,
    moduleId: 12,
    title: "Python OOP",
    description: "Object-oriented programming in Python",
    difficulty: "Medium",
    duration: 35,
    passingScore: 75,
    totalQuestions: 18,
    totalPoints: 180,
    attempts: 167,
    averageScore: 79,
    status: "published",
  },
  {
    id: 30,
    moduleId: 12,
    title: "Python Libraries",
    description: "Popular Python libraries and frameworks",
    difficulty: "Medium",
    duration: 30,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 153,
    averageScore: 81,
    status: "published",
  },
  {
    id: 31,
    moduleId: 1,
    title: "Responsive Web Design",
    description: "Creating mobile-friendly websites",
    difficulty: "Medium",
    duration: 30,
    passingScore: 75,
    totalQuestions: 15,
    totalPoints: 150,
    attempts: 189,
    averageScore: 80,
    status: "published",
  },
  {
    id: 32,
    moduleId: 2,
    title: "JavaScript Design Patterns",
    description: "Common design patterns in JavaScript",
    difficulty: "Hard",
    duration: 45,
    passingScore: 80,
    totalQuestions: 20,
    totalPoints: 200,
    attempts: 98,
    averageScore: 72,
    status: "published",
  },
  {
    id: 33,
    moduleId: 3,
    title: "State Management with Redux",
    description: "Managing complex state in React",
    difficulty: "Hard",
    duration: 40,
    passingScore: 80,
    totalQuestions: 18,
    totalPoints: 180,
    attempts: 134,
    averageScore: 74,
    status: "published",
  },
];

// ==================== ACHIEVEMENTS DATA ====================
// Minimal 10 achievements required
export const achievements = [
  {
    id: 1,
    title: "First Steps",
    description: "Complete your first module",
    category: "learning",
    icon: "🎯",
    rarity: "common",
    points: 10,
    requirement: "Complete 1 module",
    unlockCriteria: { type: "modules_completed", count: 1 },
  },
  {
    id: 2,
    title: "Fast Learner",
    description: "Complete 5 modules",
    category: "learning",
    icon: "⚡",
    rarity: "rare",
    points: 50,
    requirement: "Complete 5 modules",
    unlockCriteria: { type: "modules_completed", count: 5 },
  },
  {
    id: 3,
    title: "Knowledge Seeker",
    description: "Complete 10 modules",
    category: "learning",
    icon: "📚",
    rarity: "epic",
    points: 100,
    requirement: "Complete 10 modules",
    unlockCriteria: { type: "modules_completed", count: 10 },
  },
  {
    id: 4,
    title: "Quiz Master",
    description: "Score 100% on 10 quizzes",
    category: "mastery",
    icon: "🏆",
    rarity: "legendary",
    points: 200,
    requirement: "Get perfect scores on 10 quizzes",
    unlockCriteria: { type: "perfect_quizzes", count: 10 },
  },
  {
    id: 5,
    title: "Consistent Learner",
    description: "7-day learning streak",
    category: "consistency",
    icon: "🔥",
    rarity: "epic",
    points: 100,
    requirement: "Study for 7 consecutive days",
    unlockCriteria: { type: "streak_days", count: 7 },
  },
  {
    id: 6,
    title: "Night Owl",
    description: "Study between midnight and 5 AM",
    category: "special",
    icon: "🦉",
    rarity: "rare",
    points: 30,
    requirement: "Complete activities between 00:00-05:00",
    unlockCriteria: { type: "night_study", count: 1 },
  },
  {
    id: 7,
    title: "Early Bird",
    description: "Study before 6 AM",
    category: "special",
    icon: "🐦",
    rarity: "rare",
    points: 30,
    requirement: "Complete activities before 06:00",
    unlockCriteria: { type: "early_study", count: 1 },
  },
  {
    id: 8,
    title: "Community Helper",
    description: "Help 20 students in forum",
    category: "community",
    icon: "🤝",
    rarity: "rare",
    points: 75,
    requirement: "Post 20 helpful replies",
    unlockCriteria: { type: "helpful_replies", count: 20 },
  },
  {
    id: 9,
    title: "Perfect Score",
    description: "Achieve 100% on a difficult quiz",
    category: "mastery",
    icon: "💯",
    rarity: "epic",
    points: 150,
    requirement: "Score 100% on a Hard difficulty quiz",
    unlockCriteria: { type: "perfect_hard_quiz", count: 1 },
  },
  {
    id: 10,
    title: "Marathon Runner",
    description: "30-day learning streak",
    category: "consistency",
    icon: "🏃",
    rarity: "legendary",
    points: 300,
    requirement: "Study for 30 consecutive days",
    unlockCriteria: { type: "streak_days", count: 30 },
  },
  {
    id: 11,
    title: "Code Warrior",
    description: "Complete 50 coding challenges",
    category: "mastery",
    icon: "⚔️",
    rarity: "epic",
    points: 150,
    requirement: "Solve 50 coding problems",
    unlockCriteria: { type: "coding_challenges", count: 50 },
  },
  {
    id: 12,
    title: "Social Butterfly",
    description: "Create 10 forum threads",
    category: "community",
    icon: "🦋",
    rarity: "common",
    points: 25,
    requirement: "Start 10 discussions",
    unlockCriteria: { type: "threads_created", count: 10 },
  },
  {
    id: 13,
    title: "Speed Demon",
    description: "Complete a quiz in under 10 minutes",
    category: "special",
    icon: "⚡",
    rarity: "rare",
    points: 50,
    requirement: "Finish quiz with 100% in <10 minutes",
    unlockCriteria: { type: "speed_quiz", time: 600, score: 100 },
  },
  {
    id: 14,
    title: "Polyglot",
    description: "Complete modules in 3 different categories",
    category: "learning",
    icon: "🌐",
    rarity: "rare",
    points: 60,
    requirement: "Complete modules from 3 categories",
    unlockCriteria: { type: "module_categories", count: 3 },
  },
  {
    id: 15,
    title: "Teaching Assistant",
    description: "Get 50 upvotes on forum answers",
    category: "community",
    icon: "👨‍🏫",
    rarity: "epic",
    points: 120,
    requirement: "Receive 50 upvotes total",
    unlockCriteria: { type: "total_upvotes", count: 50 },
  },
];

// Export all data as a single object for easy import
export default {
  modules,
  quizzes,
  achievements,
};
